#!/bin/bash
# 🚀 ZENTRAW WSL AUTO-SETUP SCRIPT
# Executa automaticamente a configuração do ambiente Zentraw no WSL

set -e  # Exit on error

ZENTRAW_REPO="https://github.com/dvitoriano01/zentraw.git"
ZENTRAW_BRANCH="Feat_Admin_Panel_V1.0.0.0"
PROJECT_DIR="$HOME/zentraw"

echo "🎯 ZENTRAW WSL AUTO-SETUP INICIANDO..."
echo "========================================"

# Function to print status
print_status() {
    echo ""
    echo "✅ $1"
    echo "----------------------------------------"
}

print_error() {
    echo ""
    echo "❌ ERRO: $1"
    echo "----------------------------------------"
    exit 1
}

# Check if running in WSL
if [[ ! -f /proc/version ]] || ! grep -qi "microsoft\|wsl" /proc/version; then
    # Additional check for WSL2
    if [[ ! -f /proc/sys/kernel/osrelease ]] || ! grep -qi "microsoft\|wsl" /proc/sys/kernel/osrelease; then
        # If both fail, check if we're in a Linux environment at least
        if [[ ! -f /etc/os-release ]]; then
            print_error "Este script deve ser executado no WSL Ubuntu!"
        fi
    fi
fi

print_status "Sistema WSL detectado - continuando setup..."

# Update system
print_status "Atualizando sistema Ubuntu..."
sudo apt update && sudo apt upgrade -y

# Install essential tools
print_status "Instalando ferramentas essenciais..."
sudo apt install -y git curl wget build-essential

# Install NVM and Node.js
print_status "Instalando Node.js via NVM..."
if [[ ! -d "$HOME/.nvm" ]]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
fi

# Source NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Install Node 18
nvm install 18
nvm use 18
nvm alias default 18

print_status "Node.js $(node --version) instalado com sucesso!"

# Configure Git (you'll need to set your own credentials)
print_status "Configurando Git..."
read -p "Digite seu nome para Git (ex: dvitoriano01): " git_name
read -p "Digite seu email para Git: " git_email

git config --global user.name "$git_name"
git config --global user.email "$git_email"

print_status "Git configurado: $git_name <$git_email>"

# Clone Zentraw repository
print_status "Clonando repositório Zentraw..."
if [[ -d "$PROJECT_DIR" ]]; then
    echo "Diretório $PROJECT_DIR já existe. Removendo..."
    rm -rf "$PROJECT_DIR"
fi

git clone "$ZENTRAW_REPO" "$PROJECT_DIR"
cd "$PROJECT_DIR"

# Checkout correct branch
git checkout "$ZENTRAW_BRANCH"

print_status "Repositório clonado e branch $ZENTRAW_BRANCH ativa"

# Install all dependencies
print_status "Instalando dependências npm (isso pode levar alguns minutos)..."

# Admin Panel
if [[ -d "Admin_Panel" ]]; then
    echo "📦 Instalando Admin Panel dependencies..."
    cd "$PROJECT_DIR/Admin_Panel"
    rm -rf node_modules package-lock.json 2>/dev/null || true
    npm install
    print_status "Admin Panel dependencies instaladas"
fi

# Template Library Builder
if [[ -d "TemplateLibraryBuilder" ]]; then
    echo "📦 Instalando Template Builder dependencies..."
    cd "$PROJECT_DIR/TemplateLibraryBuilder"
    rm -rf node_modules package-lock.json 2>/dev/null || true
    npm install
    print_status "Template Builder dependencies instaladas"
fi

# 3D Visualizer
if [[ -d "Zentraw" ]]; then
    echo "📦 Instalando 3D Visualizer dependencies..."
    cd "$PROJECT_DIR/Zentraw"
    rm -rf node_modules package-lock.json 2>/dev/null || true
    npm install
    print_status "3D Visualizer dependencies instaladas"
fi

# Create zentraw-control.sh script
print_status "Criando script de controle zentraw-control.sh..."
cd "$PROJECT_DIR"

cat > zentraw-control.sh << 'EOF'
#!/bin/bash
# Zentraw Control Script - WSL Version
# Auto-generated by zentraw-wsl-setup.sh

PROJECT_ROOT="$HOME/zentraw"

case $1 in
    start-admin)
        echo "🚀 Starting Admin Panel..."
        cd "$PROJECT_ROOT/Admin_Panel"
        npm start &
        echo "✅ Admin Panel started on http://localhost:3003"
        ;;
        
    start-template)
        echo "🚀 Starting Template Builder..."
        cd "$PROJECT_ROOT/TemplateLibraryBuilder"
        npm start &
        echo "✅ Template Builder started on http://localhost:3004"
        ;;
        
    start-3d)
        echo "🚀 Starting 3D Visualizer..."
        cd "$PROJECT_ROOT/Zentraw"
        npm start &
        echo "✅ 3D Visualizer started on http://localhost:3005"
        ;;
        
    start-all)
        echo "🚀 Starting all Zentraw services..."
        $0 start-admin
        sleep 3
        $0 start-template
        sleep 3
        $0 start-3d
        echo "✅ All Zentraw services started"
        ;;
        
    stop-all)
        echo "🛑 Stopping all Zentraw processes..."
        pkill -f "node.*300[345]" 2>/dev/null || true
        pkill -f "node.*Admin_Panel" 2>/dev/null || true
        pkill -f "node.*TemplateLibraryBuilder" 2>/dev/null || true
        pkill -f "node.*Zentraw.*server" 2>/dev/null || true
        echo "✅ All Zentraw processes stopped"
        ;;
        
    status)
        echo "📊 Zentraw Services Status:"
        echo ""
        for port in 3003 3004 3005; do
            service_name=""
            case $port in
                3003) service_name="Admin Panel" ;;
                3004) service_name="Template Builder" ;;
                3005) service_name="3D Visualizer" ;;
            esac
            
            if lsof -ti:$port >/dev/null 2>&1; then
                echo "  ✅ $service_name ($port): Running"
            else
                echo "  ❌ $service_name ($port): Not running"
            fi
        done
        ;;
        
    git-status)
        echo "📋 Git Repository Status:"
        cd "$PROJECT_ROOT"
        echo "Current branch: $(git branch --show-current)"
        echo "Last commit: $(git log -1 --pretty=format:'%h - %s (%cr)')"
        git status --short
        ;;
        
    *)
        echo "🎯 Zentraw Control Script"
        echo ""
        echo "Commands:"
        echo "  start-admin     - Start Admin Panel (3003)"
        echo "  start-template  - Start Template Builder (3004)"
        echo "  start-3d        - Start 3D Visualizer (3005)"
        echo "  start-all       - Start all services"
        echo "  stop-all        - Stop all services"
        echo "  status          - Show services status"
        echo "  git-status      - Show git status"
        ;;
esac
EOF

chmod +x zentraw-control.sh

# Create .env files if they don't exist
print_status "Verificando arquivos de configuração..."

if [[ -f "Admin_Panel/.env.example" && ! -f "Admin_Panel/.env" ]]; then
    cp "Admin_Panel/.env.example" "Admin_Panel/.env"
    echo "📄 Arquivo Admin_Panel/.env criado baseado no .env.example"
fi

# Test basic functionality
print_status "Testando funcionalidade básica..."

echo "🧪 Testando script de controle..."
./zentraw-control.sh status

echo "🧪 Testando git status..."
./zentraw-control.sh git-status

# Add useful aliases to bashrc
print_status "Adicionando aliases úteis ao ~/.bashrc..."

# Check if aliases already exist
if ! grep -q "# Zentraw aliases" ~/.bashrc; then
    cat >> ~/.bashrc << 'EOF'

# Zentraw aliases
alias zentraw='cd ~/zentraw'
alias zc='~/zentraw/zentraw-control.sh'
alias zstatus='~/zentraw/zentraw-control.sh status'
alias zstart='~/zentraw/zentraw-control.sh start-admin'
alias zstop='~/zentraw/zentraw-control.sh stop-all'

# Quick navigation
alias za='cd ~/zentraw/Admin_Panel'
alias zt='cd ~/zentraw/TemplateLibraryBuilder'
alias z3='cd ~/zentraw/Zentraw'
EOF
    
    echo "✅ Aliases adicionados ao ~/.bashrc"
    echo "   Use: zentraw, zc, zstatus, zstart, zstop, za, zt, z3"
fi

# Final verification
print_status "Verificação final..."

cd "$PROJECT_DIR"

echo "📊 Verificação do ambiente:"
echo "  ✅ WSL Ubuntu: $(lsb_release -d | cut -f2)"
echo "  ✅ Node.js: $(node --version)"
echo "  ✅ npm: $(npm --version)"
echo "  ✅ Git: $(git --version | head -1)"
echo "  ✅ Project: $(pwd)"
echo "  ✅ Branch: $(git branch --show-current)"
echo "  ✅ Control script: $(ls -la zentraw-control.sh | awk '{print $1, $9}')"

# Test Admin Panel quick start
echo ""
echo "🧪 Teste rápido do Admin Panel..."
cd "$PROJECT_DIR/Admin_Panel"

# Quick dependency check
if [[ ! -d "node_modules" ]]; then
    print_error "Node modules não encontrados no Admin Panel"
fi

if [[ ! -f "package.json" ]]; then
    print_error "package.json não encontrado no Admin Panel"
fi

echo "✅ Admin Panel está pronto para execução"

# Success message
echo ""
echo "🎉 SETUP CONCLUÍDO COM SUCESSO!"
echo "========================================"
echo ""
echo "📋 Próximos passos:"
echo "1. Para usar os aliases: source ~/.bashrc"
echo "2. Testar Admin Panel: ./zentraw-control.sh start-admin"
echo "3. Abrir VS Code: code ."
echo "4. Verificar no navegador: http://localhost:3003"
echo ""
echo "🚀 Comandos úteis:"
echo "  zentraw              # Ir para diretório do projeto"
echo "  zc status            # Ver status dos serviços"
echo "  zc start-admin       # Iniciar Admin Panel"
echo "  zc stop-all          # Parar todos os serviços"
echo "  code .               # Abrir VS Code no projeto"
echo ""
echo "📚 Documentação completa em:"
echo "  ~/zentraw/ZENTRAW_WSL_COMPLETE_SETUP_GUIDE.md"
echo ""
echo "✅ Zentraw está pronto para desenvolvimento no WSL!"
