export const freepikFonts = [
  // Fontes Google Fonts estilizadas - funcionais e disponíveis
  { label: "Orbitron", value: "Orbitron" },
  { label: "Dancing Script", value: "Dancing Script" },
  { label: "Bungee", value: "Bungee" },
  { label: "Black Ops One", value: "Black Ops One" },
  { label: "Righteous", value: "Righteous" },
  { label: "Creepster", value: "Creepster" },
  { label: "Satisfy", value: "Satisfy" },
  { label: "Press Start 2P", value: "Press Start 2P" },
  { label: "Fredoka One", value: "Fredoka One" },
  { label: "Audiowide", value: "Audiowide" },
  { label: "Bebas Neue", value: "Bebas Neue" },
  { label: "Montserrat", value: "Montserrat" },
  { label: "Oswald", value: "Oswald" },
  { label: "Poppins", value: "Poppins" },
  { label: "Roboto", value: "Roboto" },
  { label: "Anton", value: "Anton" },
  { label: "Bangers", value: "Bangers" },
  { label: "Pacifico", value: "Pacifico" },
  { label: "Lobster", value: "Lobster" },
  { label: "Comfortaa", value: "Comfortaa" },
  
  // Fontes adicionais do Google Fonts para mais variedade
  { label: "Kalam", value: "Kalam" },
  { label: "Permanent Marker", value: "Permanent Marker" },
  { label: "Bowlby One", value: "Bowlby One" },
  { label: "Shadows Into Light", value: "Shadows Into Light" },
  { label: "Covered By Your Grace", value: "Covered By Your Grace" },
  { label: "Rock Salt", value: "Rock Salt" },
  { label: "Abril Fatface", value: "Abril Fatface" },
  { label: "Crimson Text", value: "Crimson Text" },
  { label: "Lato", value: "Lato" },
  { label: "Open Sans", value: "Open Sans" },
  { label: "Source Sans Pro", value: "Source Sans Pro" },
  { label: "Ubuntu", value: "Ubuntu" },
  { label: "Raleway", value: "Raleway" },
  { label: "Nunito", value: "Nunito" },
  { label: "Playfair Display", value: "Playfair Display" },
  { label: "Merriweather", value: "Merriweather" },
  { label: "Roboto Slab", value: "Roboto Slab" },
  { label: "PT Sans", value: "PT Sans" },
  { label: "Noto Sans", value: "Noto Sans" },
  { label: "Fira Sans", value: "Fira Sans" },
  
  // Fontes criativas e artisticas
  { label: "Amatic SC", value: "Amatic SC" },
  { label: "Indie Flower", value: "Indie Flower" },
  { label: "Caveat", value: "Caveat" },
  { label: "Kaushan Script", value: "Kaushan Script" },
  { label: "Great Vibes", value: "Great Vibes" },
  { label: "Allura", value: "Allura" },
  { label: "Sacramento", value: "Sacramento" },
  { label: "Alex Brush", value: "Alex Brush" },
  { label: "Tangerine", value: "Tangerine" },
  { label: "Yellowtail", value: "Yellowtail" },
  
  // Fontes decorativas e temáticas
  { label: "Cinzel", value: "Cinzel" },
  { label: "Cinzel Decorative", value: "Cinzel Decorative" },
  { label: "Uncial Antiqua", value: "Uncial Antiqua" },
  { label: "MedievalSharp", value: "MedievalSharp" },
  { label: "Griffy", value: "Griffy" },
  { label: "Nosifer", value: "Nosifer" },
  { label: "Chela One", value: "Chela One" },
  { label: "Eater", value: "Eater" },
  { label: "Butcherman", value: "Butcherman" },
  { label: "Metal Mania", value: "Metal Mania" },
  
  // Fontes modernas e minimalistas
  { label: "Work Sans", value: "Work Sans" },
  { label: "Barlow", value: "Barlow" },
  { label: "Inter", value: "Inter" },
  { label: "Space Grotesk", value: "Space Grotesk" },
  { label: "DM Sans", value: "DM Sans" },
  { label: "Manrope", value: "Manrope" },
];
