export const freepikFonts = [
  { label: "Aerohate Caps", value: "Aerohate Aerohate Caps 400" },
  { label: "Akuina Black", value: "Akuina Akuina Black 800" },
  { label: "Akuina Black Slanted", value: "Akuina Akuina Black Slanted 800" },
  { label: "Akuina Bold", value: "Akuina Akuina Bold 700" },
  { label: "Akuina Bold Slanted", value: "Akuina Akuina Bold Slanted 700" },
  { label: "Akuina Extra Bold", value: "Akuina Akuina Extra Bold 800" },
  { label: "Akuina Light", value: "Akuina Akuina Light 200" },
  { label: "Akuina Light Slanted", value: "Akuina Akuina Light Slanted 200" },
  { label: "Akuina Medium", value: "Akuina Akuina Medium 500" },
  { label: "Akuina Medium Slanted", value: "Akuina Akuina Medium Slanted 500" },
  { label: "Akuina Slanted", value: "Akuina Akuina Regular Slanted 400" },
  { label: "Akuina Regular", value: "Akuina Regular 400" },
  { label: "Akuina Semibold", value: "Akuina Semibold 600" },
  { label: "Akuina Semibold Slanted", value: "Akuina Semibold Slanted 600" },
  { label: "Bestters Supply", value: "Bestters Supply Bestters Supply Regular 400" },
  { label: "Big Bang Slant", value: "Big Bang Big Bang Slant 400" },
  { label: "Big Bang Swashes", value: "Big Bang Big Bang Swashes 400" },
  { label: "Bilground", value: "Bilground Bilground Regular 400" },
  { label: "Birthday Dream", value: "Birthday Dream Birthday Dream Regular 400" },
  { label: "Bonitalia", value: "Bonitalia Bonitalia Regular 400" },
  { label: "Crown Ford", value: "Crown Ford Crown Ford Regular 400" },
  { label: "Custody Script", value: "Custody Custody Regular Script 400" },
  { label: "Dhaniel", value: "Dhaniel Dhaniel Regular 400" },
  { label: "Different Beginning Bold", value: "Different Beginning Different Beginning Bold 700" },
  { label: "Different Beginning Light", value: "Different Beginning Different Beginning Light 200" },
  { label: "Different Beginning", value: "Different Beginning Different Beginning Regular 400" },
  { label: "Facon", value: "Facon_Free" },
  { label: "Freedom Standing Extra Light", value: "Freedom Standing Freedom Standing Extra Light 100" },
  { label: "Freedom Standing Extra Light Italic", value: "Freedom Standing Freedom Standing Extra Light Italic 100" },
  { label: "Freedom Standing Light", value: "Freedom Standing Freedom Standing Light 200" },
  { label: "Freedom Standing Light Italic", value: "Freedom Standing Freedom Standing Light Italic 200" },
  { label: "Freedom Standing", value: "Freedom Standing Freedom Standing Regular 400" },
  { label: "Freedom Standing Italic", value: "Freedom Standing Freedom Standing Regular Italic 400" },
  { label: "Glitchgoblin", value: "Glitchgoblin_Free" },
  { label: "Guthenberg Swashes", value: "Guthenberg Guthenberg Regular Swashes 400" },
  { label: "Hericake", value: "Hericake Hericake Regular 400" },
  { label: "Holian", value: "Holian Holian Regular 400" },
  { label: "Keep Humble", value: "Keep Humble Keep Humble Regular 400" },
  { label: "Magical Sparkle", value: "Magical Sparkle Magical Sparkle Regular 400" },
  { label: "Magical Sparkle Italic", value: "Magical Sparkle Magical Sparkle Regular Italic 400" },
  { label: "Medium Unique Bold", value: "Medium Unique Medium Unique Bold 700" },
  { label: "Medium Unique", value: "Medium Unique Medium Unique Regular 400" },
  { label: "Mercy Christole", value: "Mercy Christole Mercy Christole Regular 400" },
  { label: "Milksea", value: "Milksea Milksea Regular 400" },
  { label: "Mockatea", value: "Mockatea Mockatea Regular 400" },
  { label: "Mofita", value: "Mofita Mofita 400" },
  { label: "Mofita Italic", value: "Mofita Mofita Italic 400" },
  { label: "Mofita Pro", value: "Mofita Mofita Pro 400" },
  { label: "Mofita Pro Italic", value: "Mofita Mofita Pro Italic 400" },
  { label: "Mongkrain", value: "Mongkrain Mongkrain Regular 400" },
  { label: "Morthwicks", value: "Morthwicks Morthwicks Regular 400" },
  { label: "Playride", value: "Playride Playride Regular 400" },
  { label: "Retroking", value: "Retroking Retroking Regular 400" },
  { label: "Retroking Rough", value: "Retroking Retroking Regular Rough 400" },
  { label: "The Beautyline", value: "The Beautyline The Beautyline Regular 400" },
  { label: "Tratags", value: "Tratags Tratags Regular 400" },
  { label: "Turbo Type", value: "Turbo Type Regular Turbo Type Regular 400" },
  { label: "Turbo Type Two", value: "Turbo Type Regular Turbo Type Two Regular 400" },
  { label: "Urban Starblues Graffiti", value: "Urban Starblues Urban Starblues Graffiti Regular 400" },
  { label: "Urban Starblues Sans", value: "Urban Starblues Urban Starblues Sans Regular 400" },
  { label: "Vibes Arcade", value: "Vibes Arcade Vibes Arcade Svg 400" },
  { label: "Watten", value: "Watten Watten Regular 400" },
];
