// Fontes Freepik Premium - Sistema otimizado (v1.3.0.c.2)
// Nosso diferencial: 50+ fontes exclusivas com nomes limpos e organizados
export const freepikFonts = [
  { label: "Aerohate Caps", value: "Aerohate Caps" },
  { label: "Akuina Regular", value: "Akuina" },
  { label: "Akuina Light", value: "Akuina" },
  { label: "Akuina Medium", value: "Akuina" },
  { label: "Akuina Semibold", value: "Akuina" },
  { label: "Akuina Bold", value: "Akuina" },
  { label: "Akuina Black", value: "Akuina" },
  { label: "Bestters Supply", value: "Bestters Supply" },
  { label: "Big Bang", value: "Big Bang" },
  { label: "Big Bang Swashes", value: "Big Bang Swashes" },
  { label: "Bilground", value: "Bilground" },
  { label: "Birthday Dream", value: "Birthday Dream" },
  { label: "Bonitalia", value: "Bonitalia" },
  { label: "Crown Ford", value: "Crown Ford" },
  { label: "Custody Script", value: "Custody Script" },
  { label: "Dhaniel", value: "Dhaniel" },
  { label: "Different Beginning Light", value: "Different Beginning" },
  { label: "Different Beginning Regular", value: "Different Beginning" },
  { label: "Different Beginning Bold", value: "Different Beginning" },
  { label: "Facon", value: "Facon" },
  { label: "Freedom Standing Extra Light", value: "Freedom Standing" },
  { label: "Freedom Standing Light", value: "Freedom Standing" },
  { label: "Freedom Standing Regular", value: "Freedom Standing" },
  { label: "Glitch Goblin", value: "Glitch Goblin" },
  { label: "Guthenberg Swashes", value: "Guthenberg Swashes" },
  { label: "Hericake", value: "Hericake" },
  { label: "Holian", value: "Holian" },
  { label: "Keep Humble", value: "Keep Humble" },
  { label: "Magical Sparkle Regular", value: "Magical Sparkle" },
  { label: "Magical Sparkle Italic", value: "Magical Sparkle" },
  { label: "Medium Unique Regular", value: "Medium Unique" },
  { label: "Medium Unique Bold", value: "Medium Unique" },
  { label: "Mercy Christole", value: "Mercy Christole" },
  { label: "Milksea", value: "Milksea" },
  { label: "Mockatea", value: "Mockatea" },
  { label: "Mofita Regular", value: "Mofita" },
  { label: "Mofita Italic", value: "Mofita" },
  { label: "Mofita Pro Regular", value: "Mofita Pro" },
  { label: "Mofita Pro Italic", value: "Mofita Pro" },
  { label: "Mongkrain", value: "Mongkrain" },
  { label: "Morthwicks", value: "Morthwicks" },
  { label: "Playride", value: "Playride" },
  { label: "Retroking", value: "Retroking" },
  { label: "Retroking Rough", value: "Retroking Rough" },
  { label: "The Beautyline", value: "The Beautyline" },
  { label: "Tratags", value: "Tratags" },
  { label: "Turbo Type", value: "Turbo Type" },
  { label: "Turbo Type Two", value: "Turbo Type Two" },
  { label: "Urban Starblues Graffiti", value: "Urban Starblues Graffiti" },
  { label: "Urban Starblues Sans", value: "Urban Starblues Sans" },
  { label: "Vibes Arcade", value: "Vibes Arcade" },
  { label: "Watten", value: "Watten" },
];
